[package]
name = "n_poly"
version = "0.1.0"
authors = ["Will Cashman <wcashman1351@gmail.com>"]
edition = "2018"

[dependencies]
cached = "0.11.0"
num-complex = "0.2.4"
log = "0.4.0"
env_logger = "0.7.1"
