[package]
name = "n_poly"
version = "0.1.0"
authors = ["Will Cashman <wcashman1351@gmail.com>"]
edition = "2018"

[profile.test] 
opt-level = 3

[dependencies]
num-traits = "0.2"
chrono = "0.4"
rand = "0.7"
regex = "1.3.7"
alga = "0.9.3"
rustfft = "4.1.0"
num = "0.3.1"
itertools = "0.10.0"
